### ISSUE TITLE
[suggestions] Renaming repo name

### ISSUE THREAD

**Issue by ayoubelmhamdi** [phaazon/kak-tree-sitter#1]
Hi
I think the tree-sitter modules should be following the same naming, so could you change it to:

`tree-sitter-kak`
# UPDATE 1
I believe that the naming convention for the tree-sitter parser should be consistent, and therefore, could you please change the name of our repository in GitHub to 'tree-sitter-kak'?

**Comment by phaazon** [comment]
What are you talking about exactly here when you mention _modules_?

**Comment by ayoubelmhamdi** [comment]
I see that all the parsers have names following a similar pattern such as:
- `tree-sitter-c`
- `tree-sitter-dart`
- `tree-sitter-go`
- ...

**Comment by phaazon** [comment]
This is not a parser for Kakoune.
