### ISSUE TITLE
Spawns numerous kak processes

### ISSUE THREAD

**Issue by SolitudeSF** [phaazon/kak-tree-sitter#119]
After each "refresh" a `kak` process is left.
![image](https://github.com/phaazon/kak-tree-sitter/assets/10168645/d7320302-6b03-40e4-85a7-c35b22519fbe)

**Comment by SolitudeSF** [comment]
They are closed on the exit of a server, but doesnt look like growing tree like that is supposed to happen.

**Comment by phaazon** [comment]
This is interesting. How many do you get? That might explain the weird fork problem from #10.

**Comment by phaazon** [comment]
Damn that’s likely that. I need to understand what’s going on. Fixing this should fix #10. I’ll close as a duplicate and will update the other issue.

Thanks for reaching out!
