### ISSUE TITLE
Do not remove the default highlighting by default (make it a per-lang option)

### ISSUE THREAD

**Issue by phaazon** [phaazon/kak-tree-sitter#141]
[This comment](https://github.com/phaazon/kak-tree-sitter/issues/138#issue-1910426230) explains the rationale.

**Comment by korreman** [comment]
Would it perhaps be better to have per-language control of this? Eg. allowing to whitelist a few languages in the config, but disabling the builtins for the majority of langs.

**Comment by phaazon** [comment]
Yes, that was what I had on my mind. Since we already have per-language config, it should be trivial to add an option / flag there.

**Comment by phaazon** [comment]
So the design I had with #181 is to default to removing it (`true`), and let users override it and not removing the default highlighter (`false`).

I’m updating the wiki in the meantime.
