### ISSUE TITLE
Installs grammars and queries in the wrong directory

### ISSUE THREAD

**Issue by uncomfyhalomacro** [phaazon/kak-tree-sitter#178]
Following instructions from the wiki, it says that it will install the grammars at `$XDG_CONFIG_HOME/kak-tree-sitter` or `~/.config/kak-tree-sitter/` but it installs it in `/run/user/1000/ktsctl`.

I am not sure which of it was true

Edit:

Reading the README of ktsctl, it installs at `~/.local/share/kak-tree-sitter` of which, `~/.local/share` is part of the `XDG_DATA_DIRS`. But [wiki](https://github.com/phaazon/kak-tree-sitter/wiki/ktsctl) says `XDG_CONFIG_HOME`. Is this an oopsie? At least `grammars` and `queries` are really installed there though

**Comment by uncomfyhalomacro** [comment]
I guess the wiki and this line https://github.com/phaazon/kak-tree-sitter/blob/9d8261abd1d03699055cf848df02e3c18108ed99/doc/design.md?plain=1#L112 may have caused the confusion. Not sure.

**Comment by phaazon** [comment]
Ah it’s probably a mistake, yes. It should install to `XDG_DATA_DIRS`, and read the config from `XDG_CONFIG_HOME`. Thanks for reporting!

**Comment by uncomfyhalomacro** [comment]
> Ah it’s probably a mistake, yes. It should install to `XDG_DATA_DIRS`, and read the config from `XDG_CONFIG_HOME`. Thanks for reporting!

That's just an inconsistency between the wiki and the README so I can just edit that and close this.

**Comment by phaazon** [comment]
I updated both the README and the wiki. Thanks again for reporting!
