### ISSUE TITLE
Freeze on a specific JS file

### ISSUE THREAD

**Issue by postsolar** [phaazon/kak-tree-sitter#192]
KTS version: kak-tree-sitter 0.5.2-dev-7bb2a67

There's a specific JS file on which my Kakoune session freezes as soon as I make any movement in the buffer (e.g. press j, k, e, etc). Interacting with Kakoune in other ways (e.g. the prompt) does not cause freezes. Trying to clear dead sessions afterwards makes that command freeze, as well as trying to connect to frozen session. I have tried it with an empty config file and empty autoload folder as well (just the KTS startup command). Kakoune version is current master.

This file is my config for a GTK widgets lib and isn't suspicious in any way. It behaves fine with Helix and with tree-sitter-cli.

Attached is this file, with changed extension (Github doesn't let `.js` in).
[config.txt](https://github.com/phaazon/kak-tree-sitter/files/13551378/config.txt)

Please look if you can reproduce it, that's very weird indeed

**Comment by phaazon** [comment]
Nope, I can’t reproduce on my system.
<img width="1678" alt="Screenshot 2023-12-04 at 22 46 18" src="https://github.com/phaazon/kak-tree-sitter/assets/506592/7360b8d1-9fe0-4c82-af54-efc0428cb02e">

**Comment by phaazon** [comment]
May you try to:

1. Compile Kakoune in debug mode.
2. Open that file to reproduce the bug.
3. Use `gdb` to attach to the pid of Kakoune, and provide a backtrace.

Also, which operating system are you using?

**Comment by postsolar** [comment]
It might be due to Kakoune standard modules acting on code on buffer initialization.

https://github.com/mawww/kakoune/blob/7f49395cf931b2af8a75ffb5319a8aa8c395ed8d/rc/filetype/javascript.kak#L15-L22

In fact if I turn off everything but the standard modules then this file "starts" with an edit history🤯.
I didn't even know it's a thing. Anyways, if I disable standard modules loading then it's fine, so probably unrelated to KTS.

**Comment by phaazon** [comment]
Okay, feel free to reopen if that happens again!
