### ISSUE TITLE
ktsctl: Allow multiple compile commands?

### ISSUE THREAD

**Issue by korreman** [phaazon/kak-tree-sitter#32]
In contrast to most other grammars, [tree-sitter-python](https://github.com/tree-sitter/tree-sitter-python) contains both a C and C++ file, which must be compiled with `cc` and `c++` respectively, then linked with `c++`. 

It's likely possible to hack a solution using `sh` to run both compile commands from ktsctl, but it's probably preferable to properly support separate compilation of the scanner and parser.

**Comment by phaazon** [comment]
I’m compiling those without any issue with `cc`. It’s already the case with many grammars, like [bash](https://github.com/phaazon/kak-tree-sitter/blob/master/config.toml#L133), [C++](https://github.com/phaazon/kak-tree-sitter/blob/master/config.toml#L217), [yaml](https://github.com/phaazon/kak-tree-sitter/blob/master/config.toml#L806), etc.

**Comment by korreman** [comment]
My bad, I just needed to add the `-lstdc++` flag to the linking command.
