### ISSUE TITLE
Highlighting breaks when first line is empty

### ISSUE THREAD

**Issue by korreman** [phaazon/kak-tree-sitter#40]
Reproduction: Open kakoune such that it is highlighting a Rust buffer with `kak-tree-sitter` (fx. `...kak-tree-sitter/src/cli.rs`). Verify that the file is being highlighted. Insert a newline at the beginning of the file. The highlighting will disappear or break in other ways. Remove the newline and highlighting returns.

This has been reproduced on Linux with an empty configuration save for a single `eval %sh{kak-tree-sitter -dk}`. It only seems to be an issue with for grammars.

**Comment by phaazon** [comment]
Yeah, I saw that as well with commit messages, using the `git-commit` grammar. To add more nuance, it doesn’t break `kak-tree-sitter`, it just removes the default highlighter, if any, but then adding text fixes highlighting.

That is a bit weird and I need to understand why it does that. I’ll investigate today.
