### ISSUE TITLE
More intelligent auto-enable

### ISSUE THREAD

**Issue by korreman** [phaazon/kak-tree-sitter#45]
Currently, opening a file with an unsupported filetype, then changing the filetype to a supported one will not enable highlighting.

In a similar vein, try opening a supported file, then opening an unsupported buffer from the first client (`:new edit foo`). The client of the second buffer will repeatedly attempt to highlight the buffer with a constant "unsupported language" message.

It would be nice if highlighting was automatically enabled or disabled for every buffer whenever its filetype is set/modified.

**Comment by phaazon** [comment]
I agree. This will closely relate to #20.

We can do that with a hook on `BufSetOption filetype`; it should be fairly simple. Also, just to add to your comment, I want that to also be possible when restarting KTS. Currently, restarting KTS while Kakoune is open seems to prevent Kakoune from understanding the restart.

**Comment by phaazon** [comment]
Done in #20.
