### ISSUE TITLE
ktsctl cannot install parser & grammar

### ISSUE THREAD

**Issue by YuFei29** [phaazon/kak-tree-sitter#55]
I installed ktsctl and kak-tree-sitter via cargo.I have copy config file to .config/kak-tree-sitter

when i try to install  tree-sitter parser i get error: configuration error: cannot read configuration: No such file or directory (os error 2)
I think it tell me there's something wrong in my config file but I don't know what's wrong here.
<img width="1288" alt="Screenshot 2023-07-01 at 21 10 19" src="https://github.com/phaazon/kak-tree-sitter/assets/125109356/d7681239-9453-4c93-88fe-0a21ebf23c3f">

my os version is: OS: macOS 13.4.1 22F82 x86_64

**Comment by phaazon** [comment]
Thanks, I’m having a look! It’s probably due to the fact you should be putting that in `~/Library/Application\ Support/kak-tree-sitter` instead.

**Comment by phaazon** [comment]
Yes, confirmed, you need a configuration file located in the right place. See [this](https://github.com/phaazon/kak-tree-sitter/wiki/Configuration).
